name: py3p6
channels:
  - https://repo.anaconda.com/pkgs/free
  - conda-forge
  - bccp
  - anaconda
  - defaults
dependencies:
  - appnope=0.1.0=py36hf537a9a_0
  - asn1crypto=0.24.0=py36_0
  - astropy=3.2.1=py36h1de35cc_0
  - atomicwrites=1.3.0=py36_1
  - attrs=19.1.0=py36_1
  - backcall=0.1.0=py36_0
  - basemap=1.2.0=py36h0acbc05_0
  - beautifulsoup4=4.7.1=py36_1
  - bigfile=0.1.47=py36hdb31825_6
  - blas=1.0=mkl
  - bleach=3.1.0=py36_0
  - bokeh=1.3.4=py36_0
  - boost=1.67.0=py36_4
  - bzip2=1.0.8=h1de35cc_0
  - ca-certificates=2019.11.28=hecc5488_0
  - cachey=0.1.1=py36h814b9ca_0
  - cartopy=0.16.0=py36h9263bd1_0
  - certifi=2019.11.28=py36h9f0ad1d_1
  - cffi=1.12.3=py36hb5b8e2f_0
  - chardet=3.0.4=py36_1003
  - classylss=0.2.9=py36h8516146_7
  - click=7.0=py36_0
  - cloog=0.18.0=0
  - cloudpickle=1.2.1=py_0
  - corrfunc=2.3.0=py36hdb31825_10
  - coverage=4.5.3=py36h1de35cc_0
  - cryptography=2.7=py36ha12b0ac_0
  - cycler=0.10.0=py36hfc81398_0
  - cython=0.29.12=py36h0a44026_0
  - cytoolz=0.10.0=py36h1de35cc_0
  - dask=2.2.0=py_0
  - dask-core=2.2.0=py_0
  - decorator=4.4.0=py36_1
  - defusedxml=0.6.0=py_0
  - distributed=2.2.0=py_1
  - entrypoints=0.3=py36_0
  - expat=2.2.6=h0a44026_0
  - fastcache=1.1.0=py36h1de35cc_0
  - fitsio=1.0.5=py36hdb31825_5
  - freetype=2.9.1=hb4e5f40_0
  - fsspec=0.4.0=py_0
  - future=0.17.1=py36_0
  - gcc=4.8.2=5
  - geos=3.6.2=h5470d99_2
  - gettext=0.19.8.1=h15daf44_3
  - git=2.20.1=pl526h6951d83_0
  - glib=2.56.2=hd9629dc_0
  - gmp=6.1.2=hb37e062_1
  - gmpy2=2.0.8=py36hf9c35bd_2
  - gsl=2.4=h1de35cc_4
  - h5py=2.9.0=py36h3134771_0
  - halotools=0.6=py36hcc8010b_5
  - hdf5=1.10.4=hfa1e0ec_0
  - healpy=1.12.9=py36h7cee5ec_0
  - heapdict=1.0.0=py36_2
  - icu=58.2=h4b95b61_1
  - idna=2.8=py36_0
  - importlib_metadata=0.19=py36_0
  - intel-openmp=2019.4=233
  - ipykernel=5.1.1=py36h39e3cac_0
  - ipython=7.7.0=py36h39e3cac_0
  - ipython_genutils=0.2.0=py36h241746c_0
  - isl=0.12.2=1
  - jedi=0.13.3=py36_0
  - jinja2=2.10.1=py36_0
  - joblib=0.13.2=py36_0
  - jpeg=9b=he5867d9_2
  - jsonschema=3.0.1=py36_0
  - jupyter_client=5.3.1=py_0
  - jupyter_core=4.5.0=py_0
  - kdcount=0.3.29=py36hdb31825_5
  - kiwisolver=1.1.0=py36h0a44026_0
  - krb5=1.16.1=hddcf347_7
  - libboost=1.67.0=hebc422b_4
  - libcurl=7.65.2=h051b688_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.15=hdd342a3_7
  - libpng=1.6.37=ha441bb4_0
  - libsodium=1.0.16=h3efe00b_0
  - libssh2=1.8.2=ha12b0ac_0
  - libtiff=4.0.10=hcb84e12_2
  - libxml2=2.9.9=hf6e021a_1
  - libxslt=1.1.33=h33a18ac_0
  - llvm-openmp=4.0.1=hcfea43d_1
  - locket=0.2.0=py36hca03003_1
  - lxml=4.5.0=py36hef8c89e_0
  - markupsafe=1.1.1=py36h1de35cc_0
  - matplotlib=3.1.0=py36h54f8f79_0
  - mcfit=0.0.16=py36hc873e9d_1
  - mistune=0.8.4=py36h1de35cc_0
  - mkl=2019.4=233
  - mkl-service=2.0.2=py36h1de35cc_0
  - mkl_fft=1.0.12=py36h5e564d8_0
  - mkl_random=1.0.2=py36h27c97d8_0
  - more-itertools=7.2.0=py36_0
  - mpc=1.0.3=h7a72875_5
  - mpfr=3.1.5=h711e7fd_2
  - mpi=1.0=mpich
  - mpi4py=3.0.2=py36h77202c6_1
  - mpich=3.2.1=h12d9a10_8
  - mpmath=1.1.0=py36_0
  - mpsort=0.1.17=py36h3e21bca_7
  - msgpack-python=0.6.1=py36h04f5b5a_1
  - nbconvert=5.5.0=py_0
  - nbformat=4.4.0=py36h827af21_0
  - nbodykit=0.3.13=py36hc873e9d_5
  - ncurses=6.1=h0a44026_1
  - numexpr=2.6.9=py36h7413580_0
  - numpy=1.16.4=py36hacdab7b_0
  - numpy-base=1.16.4=py36h6575580_0
  - olefile=0.46=py36_0
  - openssl=1.1.1e=h0b31af3_0
  - owslib=0.18.0=py_0
  - packaging=19.0=py36_0
  - pandas=0.25.0=py36h0a44026_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - parso=0.5.0=py_0
  - partd=1.0.0=py_0
  - patsy=0.5.1=py36_0
  - pcre=8.43=h0a44026_0
  - perl=5.26.2=h4e221da_0
  - pexpect=4.7.0=py36_0
  - pfft-python=0.1.20=py36h3e21bca_8
  - pickleshare=0.7.5=py36_0
  - pillow=6.1.0=py36hb68e598_0
  - pluggy=0.12.0=py_0
  - pmesh=0.1.54=py36hdb31825_4
  - proj4=5.0.1=h1de35cc_0
  - prompt_toolkit=2.0.9=py36_0
  - psutil=5.6.3=py36h1de35cc_0
  - ptyprocess=0.6.0=py36_0
  - py=1.8.0=py36_0
  - py-boost=1.67.0=py36h6440ff4_4
  - pycparser=2.19=py36_0
  - pyepsg=0.4.0=py36_0
  - pygments=2.4.2=py_0
  - pyopenssl=19.0.0=py36_0
  - pyparsing=2.4.0=py_0
  - pyproj=1.9.5.1=py36h833a5d7_1
  - pyrsistent=0.14.11=py36h1de35cc_0
  - pyshp=2.1.0=py_0
  - pysocks=1.7.0=py36_0
  - pytest=5.0.1=py36_0
  - pytest-arraydiff=0.3=py36h39e3cac_0
  - pytest-astropy=0.5.0=py36_0
  - pytest-doctestplus=0.3.0=py36_0
  - pytest-openfiles=0.3.2=py36_0
  - pytest-remotedata=0.3.2=py36_0
  - pytest-runner=5.1=py_0
  - python=3.6.9=h359304d_0
  - python-dateutil=2.8.0=py36_0
  - python_abi=3.6=1_cp36m
  - pytz=2019.1=py_0
  - pyyaml=5.1.1=py36h1de35cc_0
  - pyzmq=18.0.0=py36h0a44026_0
  - readline=7.0=h1de35cc_5
  - requests=2.22.0=py36_0
  - runtests=0.0.27=py36_2
  - scikit-learn=0.21.2=py36h27c97d8_0
  - scipy=1.3.0=py36h1410ff5_0
  - seaborn=0.9.0=py36_0
  - shapely=1.6.4=py36h20de77a_0
  - six=1.12.0=py36_0
  - sortedcontainers=2.1.0=py36_0
  - soupsieve=1.9.2=py36_0
  - sqlite=3.29.0=ha441bb4_0
  - statsmodels=0.10.1=py36h1d22016_0
  - sympy=1.4=py36_0
  - tblib=1.4.0=py_0
  - testpath=0.4.2=py36_0
  - tk=8.6.8=ha441bb4_0
  - toolz=0.10.0=py_0
  - tornado=6.0.3=py36h1de35cc_0
  - traitlets=4.3.2=py36h65bd3ce_0
  - urllib3=1.24.2=py36_0
  - wcwidth=0.1.7=py36h8c6ec74_0
  - webencodings=0.5.1=py36_1
  - wheel=0.33.4=py36_0
  - wurlitzer=1.0.3=py36_0
  - xz=5.2.4=h1de35cc_4
  - yaml=0.1.7=hc338f04_2
  - zeromq=4.3.1=h0a44026_3
  - zict=1.0.0=py_0
  - zipp=0.5.2=py_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.3.7=h5bba6e5_0
  - pip:
    - absl-py==0.8.1
    - astor==0.6.2
    - gast==0.2.0
    - google-pasta==0.1.7
    - grpcio==1.12.1
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - markdown==2.6.11
    - pip==19.2.2
    - protobuf==3.10.0
    - pymangle==0.9.0
    - setuptools==39.1.0
    - tables==3.4.4
    - tb-nightly==1.9.0a20180613
    - tensorboard==1.14.0
    - tensorflow==1.14.0
    - tensorflow-estimator==1.14.0
    - termcolor==1.1.0
    - tf-nightly==1.10.0.dev20180614
    - werkzeug==0.14.1
    - wrapt==1.11.2
prefix: /Users/rezaie/anaconda3/envs/py3p6

